### ISSUE TITLE
Allow for any host

### ISSUE THREAD

**Issue by bolton** [mayo/metalsmith-serve#16]
There is currently no way to set host as null, as the default is localhost, and if you pass in null, it is overwritten by the default. Not assigning a host is useful if I want to do some quick internal testing on other devices, e.g. to have my iPhone hit my mac ip address to look at the site, but since the http server is only listening on localhost, it wont work, unless I get the IP address of my mac, and update the options to have it.

If you changed defaults.host = null, then it defaults to null, but still allows someone to set localhost if they desire.

**Comment by mayo** [comment]
@bolton You can use 0.0.0.0 for hostname if you want to listen on all interfaces.
